---
app_name: "NovaSphere"
app_version: "2.0"
env: "dev"
http_port: 80

packages:
  - nginx
  - curl
  - htop
  - tree
  - jq

nginx_server_name: "_"
nginx_root: "/var/www/html"

app_users:
  - name: deployer
    comment: "Compte de déploiement NovaSphere"
    shell: /bin/bash

  - name: monitoring
    comment: "Compte de monitoring"
    shell: /usr/sbin/nologin
